apiVersion: v1
kind: Pod
metadata:
  name: server
spec:
  containers:
  - image: nginx
    name: nginx
    volumeMounts:
    - mountPath: /tmp
      name: git-volume
  volumes:
  - name: git-volume
    gitRepo:
      repository: "git@github.com:wanghongjun2014/k8s.git"
      revision: "2cf62ab"
